# 배열 만들기

In [2]:
import numpy as np

In [6]:
a=np.array([0,1,2,3])
a
#print(a)

[0 1 2 3]


In [15]:
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)

(4,)
4
int32
1


In [12]:
li=[0,1,2,3]
np.array(li)

array([0, 1, 2, 3])

In [20]:
a=np.array([0,1,2,3,4.3])
a.dtype

dtype('float64')

In [21]:
a=np.array([0,1,2,3,4.0],dtype='int')
a.dtype

dtype('int32')

In [22]:
a

array([0, 1, 2, 3, 4])

In [23]:
a=np.array([0,1,2,3])

In [24]:
a

array([0, 1, 2, 3])

In [25]:
a=np.array([0,1,2,3],dtype='float')
a

array([0., 1., 2., 3.])

In [28]:
a. dtype

dtype('float64')

In [29]:
a=np.array([0,1,2,3],dtype='float32')
a.dtype

dtype('float32')

In [34]:
a=np.array([0,1,2,3],dtype='float16')
a.dtype

dtype('float16')

In [35]:
a=np.array([0,1,2,3],dtype='int16')
a.dtype

dtype('int16')

In [36]:
a=np.array([0,1,2,3],dtype='int8')
a.dtype

dtype('int8')

- 파이썬과 넘파이 계산 속도 비교

In [39]:
list1=[1,2,3,4]
list2=[1,2,3,4]

In [46]:
list3=[]
for i in range(4):
    list3.append(list1[i]+list2[i])
list3

[2, 4, 6, 8]

In [48]:
array1=np.array([1,2,3,4])
array2=np.array([1,2,3,4])

In [49]:
array3=array1+array2
array3

array([2, 4, 6, 8])

In [72]:
def add_list(n):
    li1=list(range(1,n+1))
    li2=list(range(1,n+1))
    
    li3=[]
    for i in range(n):
        li3.append(li1[i]+li2[i])
        
    return li3

add_list(10)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [107]:
def add_array():
    array1=np.array(range(1000))
    array2=np.array(range(1000))
    array3=array1+array2
        
    return array3

add_array()

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  3

In [102]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
def add_list():
    li1=list(range(10000))
    li2=list(range(10000))
    
    li3=[]
    for i in range(10000):
        li3.append(li1[i]+li2[i])
        
    return li3

add_list()

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [122]:
import timeit

In [123]:
timeit.timeit(add_list,number=10)

0.011933100000533159

In [124]:
print(timeit.timeit(add_list,number=1000))
print(timeit.timeit(add_array,number=1000))

1.0286015000001498
0.10155040000063309


In [128]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [129]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- 2차원 만들기

In [130]:
np.arange(10).reshape( (2,5) )

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [131]:
np.arange(12).reshape( (3,4) )

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
np.arange(12).reshape( (3,-1) )   #-1은 자동으로 잡아준다.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [145]:
np.arange(24).reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [147]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [149]:
np.arange(36).reshape(3,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [153]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)
a+b

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 6,  8],
       [10, 12]])

In [155]:
a**b

array([[    1,    64],
       [ 2187, 65536]], dtype=int32)

In [162]:
print(a)
c=np.array([5,6])
c



[[1 2]
 [3 4]]


array([5, 6])

In [161]:
a+c

array([[ 6,  8],
       [ 8, 10]])

In [164]:
c=np.array([5])
a+c

array([[6, 7],
       [8, 9]])

In [165]:
a+5

array([[6, 7],
       [8, 9]])

In [179]:
a=np.array([[1,2,3,4],[4,5,6,7]])
c=np.array([5])


In [174]:
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [180]:
c

array([5])

In [181]:
a+c

array([[ 6,  7,  8,  9],
       [ 9, 10, 11, 12]])

In [185]:
np.arange([1,2,3,4],)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [187]:
np.arange(25).reshape(1,5,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [193]:
a=np.arange([(5:5),(1:5),(3:5)])

SyntaxError: invalid syntax (2814474903.py, line 1)

In [197]:
a=np.array(range(25).reshape(5.5))a[4,:]

SyntaxError: invalid syntax (4104288781.py, line 1)

In [228]:
a=np.arange(25).reshape(5,5)
print(a[4])
print(a[:,1]a[:,3])
print(a[1,1],a[2,2],a[1,3]a[2,3])

SyntaxError: invalid syntax (2999934336.py, line 3)

In [215]:
np.arange(25).reshape(5,5) #노랑
print(a[4])

4


In [229]:
a=np.arange(25).reshape(5,5)
print(a[4])

[20 21 22 23 24]


In [235]:
a=np.arange(25).reshape(5,5)  #빨강
print(a[:,1])
print(a[:,3])

[ 1  6 11 16 21]
[ 3  8 13 18 23]


In [283]:
a=np.arange(25).reshape(5,5)  #빨강
print((a[:,1]),(a[:,3]))

[ 1  6 11 16 21] [ 3  8 13 18 23]


In [254]:
a=np.arange(25).reshape(5,5)  #파랑
print(a[1,0])
print(a[1,2])
print(a[3,0])
print(a[3,2])

5
7
15
17


In [286]:
a=np.arange(25).reshape(5,5) 
a[1::2,0:3:2]

array([[ 5,  7],
       [15, 17]])

In [289]:
a=np.arange(25).reshape(5,5) 
a[1::2,0:3:2]

array([[ 5,  7],
       [15, 17]])

In [282]:
np.arange(25).reshape(5,5)
print(a[4])
print(a[:,1])
print(a[:,3])
print(a[1,0])
print(a[1,2])
print(a[3,0])
print(a[3,2])

[20 21 22 23 24]
[ 1  6 11 16 21]
[ 3  8 13 18 23]
5
7
15
17


In [256]:
a=np.arange(25).reshape(5,5)
a[4] 

array([20, 21, 22, 23, 24])

In [280]:
print(a[0::1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [272]:
np.arange(25).reshape(5,5)
a[0::]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])