In [4]:
import numpy as np
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [6]:
np.linspace(1,9,5)

array([1., 3., 5., 7., 9.])

In [10]:
np.ones((2,3),dtype='int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#sparse matrix(드문 행렬)=희소행렬,희귀행렬
10x10 대부분 0
행렬 이름: a
3핼 3열 부분:1
5행 6열 부분:1

In [20]:
zero=np.zeros((10,10))
zero[3,3]=1
zero[5,6]=1
zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
a=np.zeros((10,10))
a[3,3]=1
a[5,6]=1
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
#모든 원소기 3인 10*10 array

In [36]:
a=np.ones((10,10))
a*3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [40]:
np.full((10,10),3)

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [50]:
a=np.array([0,1,2])  #a를 2번 반복
np.tile(a,2)

array([0, 1, 2, 0, 1, 2])

In [51]:
np.tile(a,(3,2))   #a를 2번 3행 반복 그래서 6개가 나옴

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [52]:
np.empty((2,3))

array([[1., 0., 0.],
       [1., 0., 0.]])

In [53]:
a=np.arange(6).reshape(2,3)


array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [58]:
a=[1,2,3,4]

In [59]:
b=a
b

[1, 2, 3, 4]

In [60]:
c=a.copy()
c

[1, 2, 3, 4]

In [63]:
import copy
d=copy.copy(a)
d

[1, 2, 3, 4]

In [64]:
b[0]=100
b

[100, 2, 3, 4]

In [66]:
a

[100, 2, 3, 4]

In [67]:
c

[1, 2, 3, 4]

In [68]:
d

[1, 2, 3, 4]

In [69]:
print(id(a))
print(id(b))
print(id(c))
print(id(d))

2202983737216
2202983737216
2202982408896
2202984373760


In [70]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [71]:
b=a
b

array([1, 2, 3, 4])

In [72]:
c=a.copy()
c

array([1, 2, 3, 4])

In [73]:
import copy
d=copy.copy(a)
d

array([1, 2, 3, 4])

In [74]:
b[0]=100
b

array([100,   2,   3,   4])

In [75]:
a

array([100,   2,   3,   4])

In [76]:
b

array([100,   2,   3,   4])

In [77]:
c

array([1, 2, 3, 4])

In [78]:
d

array([1, 2, 3, 4])

In [79]:
np.arange(1,9,2)
np.linspace(0,1,6)
np.ones((3,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [88]:
a=np.arange(10)*10
b=np.arange(10)*20

In [93]:
np.vstack((a,b))

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [  0,  20,  40,  60,  80, 100, 120, 140, 160, 180]])

In [94]:
np.hstack((a,b))

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90,   0,  20,  40,
        60,  80, 100, 120, 140, 160, 180])

In [96]:
np.hstack((a,b)).shape

(20,)

In [99]:
a=np.array([[1],[2],[3]])
print(a.shape)
a

(3, 1)


array([[1],
       [2],
       [3]])

In [101]:
b=np.array([[1],[2],[3]])
b

array([[1],
       [2],
       [3]])

In [102]:
np.hstack((a,b))

array([[1, 1],
       [2, 2],
       [3, 3]])

In [104]:
np.dstack((a,b))

array([[[1, 1]],

       [[2, 2]],

       [[3, 3]]])

In [131]:
a=np.arange(32).reshape(4,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [132]:
np.hsplit(a,2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

In [133]:
np.vsplit(a,4)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31]])]

In [134]:
a=np.arange(32)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [138]:
a.shape

(32,)

In [139]:
a.flatten().shape

(32,)

In [153]:
a=np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [154]:
np.hsplit(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [155]:
a.T

array([1, 2, 3, 4, 5, 6])

In [156]:
np.transpose(a)

array([1, 2, 3, 4, 5, 6])

In [157]:
np.swapaxes(a,0,1)

AxisError: axis2: axis 1 is out of bounds for array of dimension 1

In [158]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [163]:
a
b

array([4, 5, 6])

In [168]:
c=np.vstack((a,b))
np.vsplit(c,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [165]:
c = np.vstack((a,b))
np.vsplit(c,2) 

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [169]:
a = np.arange(1,5).reshape(2,2)
a.T

array([[1, 3],
       [2, 4]])

- 비교

In [171]:
a=np.array([1,2,3,4])
b=np.array([1,3,4,2])
a==b

array([ True, False, False, False])

In [173]:
a>2

array([False, False,  True,  True])

In [172]:
a[a>2]

array([3, 4])

- 정렬(sort)

In [174]:
a=np.array([1,3,4,2])
a

array([1, 3, 4, 2])

In [175]:
np.sort(a)

array([1, 2, 3, 4])

In [180]:
a.sort()

In [181]:
a

array([1, 2, 3, 4])

In [185]:
a[: ]

array([1, 2, 3, 4])

In [186]:
a[ : :-1]

array([4, 3, 2, 1])

In [189]:
x=np.array([[2,1,6],[0,7,4],[5,3,2]])
x

array([[2, 1, 6],
       [0, 7, 4],
       [5, 3, 2]])

In [191]:
np.sort(x)

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

In [192]:
np.sort(x,axis=0)  #row-wise

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

In [193]:
np.sort(x,axis=1)

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

In [202]:
a=np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [213]:
print(a[0::6])

[[0 1 2 3 4 5]]


In [214]:
a = np.array([0,1,2,3,4,5])
b = np.array([[0],[10],[20],[30],[40],[50]])
a+b 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [215]:
a = np.arange(6).reshape(1,-1)
b = np.arange(10,16).reshape(1,-1)
c = np.arange(20,26).reshape(1,-1)
d = np.arange(30,36).reshape(1,-1)
e = np.arange(40,46).reshape(1,-1)
f = np.arange(50,56).reshape(1,-1)
np.vstack((a,b,c,d,e,f)) 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [216]:
a = np.arange(6)
array = a.copy()
for i in range(5):
    i+=1
    array = np.vstack((array, a+10*i))
array 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [220]:
a = np.arange(100).reshape(10,10)
a 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [261]:
a = np.arange(100).reshape(10,10)
a = a[0:6:1,0:6:1]
a 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [262]:
a
a[0:6,2:3]
a[0:1,3:5]
a[4:6,4:6]

array([[44, 45],
       [54, 55]])

In [264]:
a
a[4:4:]
a[0,3:5]
a[::2]
a[2::2,0::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [270]:
b[:,2]
b[0,3:5]
b[2:5:2,0:5:2]
b[4:4]

array([], shape=(0, 6), dtype=int32)

In [278]:
a[ :5]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45]])

- Fancy Indexing

In [281]:
a=np.arange(8)*10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [282]:
a[[1,2,-3]]

array([10, 20, 50])

In [283]:
indices=[1,2,-3]
a[indices]

array([10, 20, 50])

In [287]:
mask=[False,True,True,False,False,True,False,False]
a[mask]

array([10, 20, 50])

In [290]:
mask=np.array([0,1,1,0,0,1,0,0],dtype=bool)
a[mask]

array([10, 20, 50])

In [291]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [292]:
[a[0,1],a[1,2],a[2,0],a[2,3]]

[1, 6, 8, 11]

In [294]:
a[[0,1,2,2],[2,3,3,4]]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [299]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [300]:
a[[0,1,2,3],[3,3,3,4]]

array([ 3,  8, 13, 19])

In [303]:
a=np.ones((3,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [305]:
b=np.ones((5, ))
5

5

In [306]:
a+b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [307]:
a+2

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [309]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [310]:
sum(a)

array([5, 7, 9])

In [311]:
np.sum(a)

21

In [312]:
np.sum(a,axis=0)

array([5, 7, 9])

In [314]:
np.sum(a,axis=1)

array([ 6, 15])

In [315]:
np.min(a)

1

In [316]:
np.min(a,axis=0)

array([1, 2, 3])

In [317]:
np.min(a,axis=1)

array([1, 4])

In [318]:
np.argmin(a)

0

In [319]:
np.argmax(a)

5

In [320]:
np.mean(a)

3.5

In [321]:
np.mean(a,axis=0)

array([2.5, 3.5, 4.5])

In [322]:
np.mean(a,axis=1)

array([2., 5.])

In [324]:
a.std()

1.707825127659933

In [325]:
a.std(axis=0)

array([1.5, 1.5, 1.5])

In [326]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [327]:
a**b

array([  1,  32, 729], dtype=int32)

In [328]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [329]:
np.max(a)

3

- np.where

In [337]:
a=np.array([6,7,8,9,10])

In [338]:
np.where(a>7) #return index

(array([2, 3, 4], dtype=int64),)

In [340]:
a[np.where(a>7)]

array([ 8,  9, 10])

In [339]:
index=np.where(a>7)
print(index)
a[index]

(array([2, 3, 4], dtype=int64),)


array([ 8,  9, 10])

In [344]:
np.where(a>7,"pass","fail")

array(['fail', 'fail', 'pass', 'pass', 'pass'], dtype='<U4')

In [349]:
a=np.arange(-15,15).reshape(5,6)**2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]], dtype=int32)

In [357]:
np.max(a)

225

In [351]:
np.min(a)

0

In [365]:
np.mean(a)

75.16666666666667

In [372]:
a.max(1,)
a.mean(1,)
a[np.where(a<10)] 

array([9, 4, 1, 0, 1, 4, 9], dtype=int32)

In [363]:
inde=np.where(a>10)
print(index)
a[index]

(array([2, 3, 4], dtype=int64),)


array([[  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]], dtype=int32)

In [378]:
a[a<10]
a[np.where(a<10)]

array([9, 4, 1, 0, 1, 4, 9], dtype=int32)

In [375]:
#10보디 작은 것은 모두 0으로 바꾸고, 크거나 같은 것은  1로 바꾸자.
np.where(a<10,0,1)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])