<a href="https://colab.research.google.com/github/limlimlim99/limjihyeonjjang/blob/main/pt1_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이토치(PyTorch)

* 페이스북이 초기 루아(Lua) 언어로 개발된 토치(Torch)를 파이썬 버전으로 개발하여 2017년도에 공개
* 초기에 토치(Torch)는 넘파이(NumPy) 라이브러리처럼 과학 연산을 위한 라이브러리로 공개
* 이후 GPU를 이용한 텐서 조작 및 동적 신경망 구축이 가능하도록 딥러닝 프레임워크로 발전시킴
* 파이썬답게 만들어졌고, 유연하면서도 가속화된 계산 속도를 제공


## 파이토치의 구성요소

- `torch`: 메인 네임스페이스, 텐서 등의 다양한 수학 함수가 포함
- `torch.autograd`: 자동 미분 기능을 제공하는 라이브러리
- `torch.nn`: 신경망 구축을 위한 데이터 구조나 레이어 등의 라이브러리
- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리
- `torch.optim`: SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화 알고리즘 제공
- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공
- `torch.onnx`: ONNX(Open Neural Network Exchange), 서로 다른 프레임워크 간의 모델을 공유할 때 사용


## 텐서(Tensors)

* 데이터 표현을 위한 기본 구조로 텐서(tensor)를 사용
* 텐서는 데이터를 담기위한 컨테이너(container)로서 일반적으로 수치형 데이터를 저장
* 넘파이(NumPy)의 ndarray와 유사
* GPU를 사용한 연산 가속 가능


In [ ]:
import torch
torch.__version__

'1.13.0+cu116'

# 텐서 초기화 데이터 타입

초기화되지 않은 텐서

In [ ]:
x = torch.empty(4,2)
print(x)

tensor([[2.1774e-36, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])


In [ ]:
import numpy as np
x = np.empty([4,2])
print(x)

[[6.75465998e-316 6.79038653e-313]
 [2.37663529e-312 2.14321575e-312]
 [2.37663529e-312 2.56761491e-312]
 [3.90842270e+160 3.43135775e-315]]


무작위로 초기화된 텐서

In [ ]:
x = torch.rand(4,2)
print(x)

# 0~1사이의 숫자를 균등하게 생성(랜덤)

tensor([[0.5656, 0.8075],
        [0.9670, 0.0205],
        [0.8085, 0.2939],
        [0.1716, 0.3426]])


데이터 타입(dtype)이 long이고, 0으로 채워진 텐서

In [ ]:
x = torch.zeros(4,2,dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


사용자가 입력한 값으로 텐서 초기화

In [ ]:
x = torch.tensor([3,2.3])
print(x)

tensor([3.0000, 2.3000])


2 X 4 크기, double 타입, 1로 채워진 텐서

In [ ]:
x = x.new_ones(2,4,dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


X와 같은 크기, float 타입, 무작위로 채워진 텐서

In [ ]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

# 사이즈를 튜플로 입력하지 않고 기존의 텐서를 정의

tensor([[0.9963, 0.1807, 0.5234, 0.5713],
        [0.4243, 0.0453, 0.1384, 0.2866]])


In [ ]:
x = torch.randn(5) 
print(x)

# 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성
# 생성한 값으로 다시 평균, 표준편차를 만들어 0과 1로 만들 수 있나? => X
# 샘플수를 늘릴수록 모오수에 가까워짐
# 표본을 잘 잡아야함~

tensor([ 0.7921, -0.3989,  1.4752, -0.0959,  0.2742])


텐서의 크기 계산

In [ ]:
print(x.size())

torch.Size([4, 2])


# 데이터 타입(Data Type)

| Data type | dtype | CPU tensor | GPU tensor |
| ------ | ------ | ------ | ------ |
| 32-bit floating point | `torch.float32` or `torch.float` |`torch.FloatTensor` | `torch.cuda.FloatTensor` |
| 64-bit floating point | `torch.float64` or `torch.double` |`torch.DoubleTensor` | `torch.cuda.DoubleTensor` |
| 16-bit floating point | `torch.float16` or `torch.half` |`torch.HalfTensor` | `torch.cuda.HalfTensor` |
| 8-bit integer(unsinged) | `torch.uint8` |`torch.ByteTensor` | `torch.cuda.ByteTensor` |
| 8-bit integer(singed) | `torch.int8` |`torch.CharTensor` | `torch.cuda.CharTensor` |
| 16-bit integer(signed) | `torch.int16` or `torch.short` |`torch.ShortTensor` | `torch.cuda.ShortTensor` |
| 32-bit integer(signed) | `torch.int32` or `torch.int` |`torch.IntTensor` | `torch.cuda.IntTensor` |
| 64-bit integer(signed) | `torch.int64` or `torch.long` |`torch.LongTensor` | `torch.cuda.LongTensor` |


- 몇 비트인지 보기
- float : 32
- double : 64
- half : 16

In [ ]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [ ]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [ ]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


# CUDA Tensor
- .to 메소드를 사용하여 텐서를 어떠한 장치(cpu, gpu)로도 옮길 수 있음

- NVIDIA가 만든 병렬 컴퓨팅 플랫폼 및 API 모델로, 보통 '쿠다'라고 발음한다. CUDA 플랫폼은 GPU 의 가상 명령어셋을 사용할 수 있도록 만들어주는 소프트웨어 레이어이며, NVIDIA가 만든 CUDA 코어가 장착된 GPU에서 작동


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.4130])
-0.41297101974487305
torch.float32


In [ ]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

# cuda를 이용할 수 있으면 cuda
# 아니면 cpu
# 런타임 유형을 None으로 하면 cpu가 나오고
# gpu로 설정하면 cuda가 나옴

cuda


# 다차원 텐서 표현

0D Tensor(Scalar)
- 하나의 숫자를 담고 있는 텐서(tensor)
- 축과 형상이 없음

In [ ]:
t0 = torch.tensor(0)

print(t0.ndim)
print(t0.shape)
print(to)

0
torch.Size([])
tensor(0)


# 1D Tensor(Vector)
- 값들을 저장한 리스트와 유사한 텐서
- 하나의 축이 존재

In [ ]:
t1 = torch.tensor([1,2,3])

print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


# 2D Tensor(Matrix)
- 행렬과 같은 모양으로 두개의 축이 존재
- 일반적인 수치, 통계 데이터셋이 해당
- 주로 샘플(samples)과 특성(features)을 가진 구조로 사용

In [ ]:
t2 = torch.tensor([[1,2,3],
                   [4,5,6]])

print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


# 3D Tensor
- 큐브(cube)와 같은 모양으로 세개의 축이 존재
- 데이터가 연속된 시퀀스 데이터나 시간 축이 포함된 시계열 데이터에 해당
- 주식 가격 데이터셋, 시간에 따른 질병

In [ ]:
t3 = torch.tensor([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(t3.ndim)
print(t3.shape)
print(t3)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


# 4D Tensor

In [ ]:
t4 = torch.tensor([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])

print(t4.ndim)
print(t4.shape)
print(t4)

2
torch.Size([4, 3])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


# 텐서의 연산(Operations)
- 텐서에 대한 수학 연산, 삼각함수, 비트연산, 비교연산, 집계 등 제공

In [ ]:
import math

a = torch.rand(1,2) * 2 -1 #가우시안 표준정규 분포
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.clamp(a, -0.5, 0.5))

# 즉 입력값이 min < x(input) < max 이면 x가 그대로 나오지만
# min보다 작으면 min값이, max보다 크면 max값이 나오는 구조입니다!

tensor([[ 0.7689, -0.8430]])
tensor([[0.7689, 0.8430]])
tensor([[1., -0.]])
tensor([[ 0.5000, -0.5000]])


In [ ]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,1])))  # unique: 중복된 값을 뺌

tensor([[ 0.7689, -0.8430]])
tensor(-0.8430)
tensor(0.7689)
tensor(-0.0370)
tensor(1.1398)
tensor(-0.6482)
tensor([1, 2, 3])


max와 min은 dim 인자를 줄 경우 argmax와 argmin도 함께 리턴
- argmax : 최대 값을 가진 인덱스
- argmin : 최소값을 가진 인덱스

In [ ]:
x = torch.rand(2,2)
print(x, '\n')
print(x.max(dim=0), '\n')   
print(x.max(dim=1))

# 행쪽으로 보는 것(dim=0) 세로로 비교해서 큰 값
# 열쪽으로 보는 것(dim=1) 가로로 비교해서 큰 값

tensor([[0.8558, 0.6451],
        [0.8133, 0.4987]]) 

torch.return_types.max(
values=tensor([0.8558, 0.6451]),
indices=tensor([0, 0])) 

torch.return_types.max(
values=tensor([0.8558, 0.8133]),
indices=tensor([0, 0]))


In [ ]:
x = torch.rand(2,2)
print(x, '\n')
print(x.min(dim=0), '\n')
print(x.min(dim=1))

# 행쪽으로 보는 것(dim=0) 세로로 비교해서 작은 값
# 열쪽으로 보는 것(dim=1) 가로로 비교해서 작은 값

tensor([[0.1361, 0.9497],
        [0.6095, 0.0596]]) 

torch.return_types.min(
values=tensor([0.1361, 0.0596]),
indices=tensor([0, 1])) 

torch.return_types.min(
values=tensor([0.1361, 0.0596]),
indices=tensor([0, 1]))


In [ ]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.1125, 0.1906],
        [0.1864, 0.1524]])
tensor([[0.9827, 0.0824],
        [0.8658, 0.2482]])


torch.add : 덧셈

In [ ]:
print(x+y)
print(torch.add(x,y))

tensor([[1.0952, 0.2730],
        [1.0522, 0.4006]])
tensor([[1.0952, 0.2730],
        [1.0522, 0.4006]])


결과 텐서를 인자로 제공

In [ ]:
result = torch.empty(2,4)
torch.add(x,y, out=result)
print(result)

tensor([[1.0952, 0.2730],
        [1.0522, 0.4006]])


<ipython-input-22-4be145b6d329>:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:17.)
  torch.add(x,y, out=result)


# in-place방식
- in-place방식으로 텐서의 값을 변경하는 연산 뒤에는 _"가 붙음
- x.copy_(y), x.t_()
- inplac = True방식과 똑같음
- _" 줄이 inplace=True임 => 바뀐 것으로 저장됨

In [ ]:
print(x)
print(y)
print()
y.add_(x)
print(y)

# y에다가 x를 더한 값을 y에다가 넣는다. y에 저장(x+y=y) y값이 x가 추가된 값으로 변경됨

tensor([[0.1125, 0.1906],
        [0.1864, 0.1524]])
tensor([[1.2077, 0.4636],
        [1.2386, 0.5530]])

tensor([[1.3202, 0.6543],
        [1.4251, 0.7054]])


torch.sub: 뺄셈

In [ ]:
print(x)
print(y)
print() 
print(x-y, '\n') # 새로 x값이 됨
x.sub_(y)  # x값이 저장됨
print(x)
print()
print(torch.sub(x,y))
print(x.sub(y))

tensor([[-2.5279, -1.1179],
        [-2.6637, -1.2583]])
tensor([[1.3202, 0.6543],
        [1.4251, 0.7054]])

tensor([[-3.8481, -1.7721],
        [-4.0888, -1.9637]]) 

tensor([[-3.8481, -1.7721],
        [-4.0888, -1.9637]])

tensor([[-5.1682, -2.4264],
        [-5.5139, -2.6690]])
tensor([[-5.1682, -2.4264],
        [-5.5139, -2.6690]])


torch.mul : 곱셈

In [ ]:
print(x)
print(y)
print()
print(x*y) # 새로 x값이 됨
x.mul_(y) # x값이 저장됨
print(x)
print()
print(torch.mul(x,y))
print(x.mul(y))

tensor([[-3.8481, -1.7721],
        [-4.0888, -1.9637]])
tensor([[1.3202, 0.6543],
        [1.4251, 0.7054]])

tensor([[-5.0801, -1.1594],
        [-5.8269, -1.3851]])
tensor([[-5.0801, -1.1594],
        [-5.8269, -1.3851]])

tensor([[-6.7067, -0.7586],
        [-8.3038, -0.9770]])
tensor([[-6.7067, -0.7586],
        [-8.3038, -0.9770]])


torch.div : 나눗셈

In [ ]:
print(x)
print(y)
print()
print(x/y) # 새로 x값이 됨
x.div_(y) # x값이 저장됨
print(x)
print()
print(torch.div(x,y))
print(x.div(y))

tensor([[-5.0801, -1.1594],
        [-5.8269, -1.3851]])
tensor([[1.3202, 0.6543],
        [1.4251, 0.7054]])

tensor([[-3.8481, -1.7721],
        [-4.0888, -1.9637]])
tensor([[-3.8481, -1.7721],
        [-4.0888, -1.9637]])

tensor([[-2.9148, -2.7086],
        [-2.8692, -2.7840]])
tensor([[-2.9148, -2.7086],
        [-2.8692, -2.7840]])


torch.mm : 내적(dot product)

In [ ]:
print(x)
print(y)
print()
print(torch.matmul(x,y))
z = torch.mm(x,y)
print(z)
print(torch.svd(z))  # singualr value decomposition A = U 시그마 VT
# (v의 전치 행렬)  (분리)
# 텐서별로 분리
# 행렬 분해 = 거꾸로 하는 것이다.

tensor([[-3.8481, -1.7721],
        [-4.0888, -1.9637]])
tensor([[1.3202, 0.6543],
        [1.4251, 0.7054]])

tensor([[-7.6056, -3.7676],
        [-8.1964, -4.0602]])
tensor([[-7.6056, -3.7676],
        [-8.1964, -4.0602]])
torch.return_types.svd(
U=tensor([[-0.6802, -0.7330],
        [-0.7330,  0.6802]]),
S=tensor([1.2478e+01, 2.9089e-05]),
V=tensor([[ 0.8961, -0.4439],
        [ 0.4439,  0.8961]]))


# 텐서의 조작(MainPulations)

인덱싱(indexing): NumPy처럼 인덱싱 형태로 사용가능

In [ ]:
import torch
x = torch.Tensor([[1,2], [3,4]])
print(x)

print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])
print(x[:,0])
print(x[:,0])
print(x[0,:])
print(x[1,:])


tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([1., 3.])
tensor([1., 2.])
tensor([3., 4.])


https://bigdatadiary0819.tistory.com/60

º 랜덤한 값을 가지는 텐서 생성

1. torch.rand() : 0과 1 사이의 숫자를 균등하게 생성

2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성

4. torch.randn_like() :  사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성

6. torch.randint_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성 

º 특정한 값을 가지는 텐서 생성

1. torch.arange() : 주어진 범위 내의 정수를 순서대로 생성

2. torch.ones() : 주어진 사이즈의 1로 이루어진 텐서 생성

3. torch.zeros() : 주어진 사이즈의 0으로 이루어진 텐서 생성

4. torch.ones_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

5. torch.zeros_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

6. torch.linspace() : 시작점과 끝점을 주어진 갯수만큼 균등하게 나눈 간격점을 행벡터로 출력(x 만들때 쓰임)

7. torch.logspace() : 시작점과 끝점을 주어진 갯수만큼 로그간격으로 나눈 간격점을 행벡터로 출력

(로그의 특징: 지수함수, 로그함수: 역의 관계)

view : 텐서의 크기(size)나 모양(shape)을 변경
- 기본적으로 변경 전과 후의 텐서 안의 원소 개수가 유지되어야 함
- -1로 설정되면 계산을 통해 해당 크기 값을 유추

In [ ]:
import torch
x = torch.randn(4,5)  # 4행 5열
print(x)
print(x.shape)
print(x.size())   #괄호를 유의해야 함 # shape랑 size는 같은 의미로 쓰인다~

tensor([[-1.5226, -1.8129, -0.0965,  0.1982, -1.1108],
        [-1.7059,  1.3597, -1.0962,  1.5096,  0.3277],
        [ 1.0674, -0.6119, -0.0835, -1.5871,  0.3989],
        [ 0.8142, -1.7009, -0.6997, -1.0096, -0.2390]])
torch.Size([4, 5])
torch.Size([4, 5])


In [ ]:
x = torch.FloatTensor([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

# size를 활용한 텐서 사이즈 보기
print(x.size())
# shape를 활용한 텐서 사이즈 보기
print(x.shape)
# dim을 활용한 텐서 사이즈 보기
print(x.dim())
# 1차원 사이즈 확인
print(x.size(0))
# 1차원 사이즈 확인
print(x.shape[0])

torch.Size([4, 2])
torch.Size([4, 2])
2
4
4


In [ ]:
x = torch.randn(4,5)
print(x)
print()
y = x.view(20)  # 20개를 써서 1차원으로 바뀜
print(y)
z = x.view(5,-1)
print(z)

tensor([[-1.5970, -1.5092,  0.3132, -0.0228,  1.1082],
        [ 0.2944, -1.4239, -1.7582,  0.4268,  0.3644],
        [ 0.9375, -0.4775, -1.1165,  1.2724, -0.9575],
        [ 0.8223, -1.8512,  0.9790, -0.2007, -0.2719]])

tensor([-1.5970, -1.5092,  0.3132, -0.0228,  1.1082,  0.2944, -1.4239, -1.7582,
         0.4268,  0.3644,  0.9375, -0.4775, -1.1165,  1.2724, -0.9575,  0.8223,
        -1.8512,  0.9790, -0.2007, -0.2719])
tensor([[-1.5970, -1.5092,  0.3132, -0.0228],
        [ 1.1082,  0.2944, -1.4239, -1.7582],
        [ 0.4268,  0.3644,  0.9375, -0.4775],
        [-1.1165,  1.2724, -0.9575,  0.8223],
        [-1.8512,  0.9790, -0.2007, -0.2719]])


item : 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.0953])
0.09526370465755463
torch.float32


squeeze : 차원을 축소(제거)

In [ ]:
tensor = torch.randn(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[ 1.9437,  1.4653, -0.7571],
         [ 0.0426, -0.4273,  0.2342],
         [-0.3660,  1.6981,  0.7317]]])
torch.Size([1, 3, 3])


In [ ]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[ 1.9437,  1.4653, -0.7571],
        [ 0.0426, -0.4273,  0.2342],
        [-0.3660,  1.6981,  0.7317]])
torch.Size([3, 3])


unsqueeze : 차원을 증가(생성)

In [ ]:
t = torch.rand(3,3)
print(t)
print(t.shape)

tensor([[0.6690, 0.5858, 0.5452],
        [0.4863, 0.4364, 0.5493],
        [0.2957, 0.5121, 0.2298]])
torch.Size([3, 3])


In [ ]:
tensor = t.unsqueeze(dim = 0)
print(tensor)
print(tensor.shape)

# dim을 주면 의도한 차원의 값이 하나 더 늘어남

tensor([[[0.6690, 0.5858, 0.5452],
         [0.4863, 0.4364, 0.5493],
         [0.2957, 0.5121, 0.2298]]])
torch.Size([1, 3, 3])


In [ ]:
tensor = tensor.unsqueeze(dim = 2)
print(tensor)
print(tensor.shape)

# dim을 주면 의도한 차원의 값이 하나 더 늘어남

tensor([[[[0.6690, 0.5858, 0.5452]],

         [[0.4863, 0.4364, 0.5493]],

         [[0.2957, 0.5121, 0.2298]]]])
torch.Size([1, 3, 1, 3])


stack : 텐서간 결합

In [ ]:
x = torch.FloatTensor([1,4])
print(x)
y = torch.FloatTensor([2,5])
print(y)
z = torch.FloatTensor([3,6])
print(z)
print(torch.stack([x,y,z]))

# stack을 써서 하나로 합쳐짐

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


cat: 텐서를 결합하는 메소드(concatenate)
- 넘파이의 stack 과 유사하지만 쌓을 dim이 존재함
- 해당 차원을 늘려준 후 결합

In [ ]:
a = torch.randn(1,3,3)
print(a)
b = torch.randn(1,3,3)
print(b)
print()

c = torch.cat((a,b), dim=0)
print(c)
print(c.size())



# 1,3,3
# 1,3,3
# dim=0을 줘서 1,1 0번째를 기준으로

tensor([[[ 0.1210,  0.2061, -0.8469],
         [-1.0533, -0.4217, -0.2451],
         [ 1.7318,  0.5116,  0.4228]]])
tensor([[[-0.0660,  0.2400,  0.4553],
         [-1.8291,  0.8854, -0.1782],
         [-0.5071,  0.0571, -0.9901]]])

tensor([[[ 0.1210,  0.2061, -0.8469],
         [-1.0533, -0.4217, -0.2451],
         [ 1.7318,  0.5116,  0.4228]],

        [[-0.0660,  0.2400,  0.4553],
         [-1.8291,  0.8854, -0.1782],
         [-0.5071,  0.0571, -0.9901]]])
torch.Size([2, 3, 3])


In [ ]:
c = torch.cat((a,b), dim=1)
print(c)
print(c.size())


# 안으로 다 합쳐짐
# dim=1로 해서 행이 6행이 됨
# dim을 어떻게 주냐에 따라 달라짐



# 1,3,3
# 1,3,3
# dim=1을 줘서 1번째를 기준으로

tensor([[[ 0.7002, -0.0520, -0.2084],
         [ 1.4386, -0.5344, -0.3535],
         [ 0.5268, -0.0740, -0.7541],
         [ 0.5788,  0.2030,  1.4530],
         [-0.8672, -1.2657,  0.5204],
         [-2.4125, -2.0150, -0.6124]]])
torch.Size([1, 6, 3])
