In [1]:
import numpy as np

# numpy array
- narray를 통해 다차원 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있다.
- 넘파이 array() 함수는 파이썬 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능을 수행
- 생성된 narray 배열의 shape변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음

In [ ]:
np.array() 사용법
- ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환한다.
- ndarray.shape는 ndarray의 차원과 크기를 튜플 형태로 나타내준다

In [3]:
array1=np.array([1,2,3])
print('array type:', type(array1))
print('array1 array 형태:', array1.shape)

# 1차원의 array로3대의 데이터를 가지고 있음

array type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [6]:
array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

# 2차원의 array로 2개의 로우와 3개의 칼럼을 가짐
#2*3=6개의 데이터를 가짐

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [7]:
array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태', array3.shape)

# 2차원의 array로 1개의 로우와 3개의 칼럼을 가짐

array3 type: <class 'numpy.ndarray'>
array3 array 형태 (1, 3)


In [12]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


# ndarray의 데이터 타입
- ndarray 내의 데이터 값은 숫자 값, 문자열 값, 불 값 등 모두 가능
- ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능
- 즉, 한개의 ndarray 객체에 int 와 float가 함꼐 있을 수 없다.

In [14]:
list1=[1,2,3]
print(type(list1))

<class 'list'>


In [17]:
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'numpy.ndarray'>
[1 2 3] int32


In [18]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

['1' '2' 'test'] <U11


In [19]:
list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

[1. 2. 3.] float64


In [ ]:
#int32형 데이터를 float64로 변환하고, 다시 float를 int32로 변경
#float를 int형으로 변경할 때 소수점 이하는 당연히 없어진다

In [21]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

[1. 2. 3.] float64


In [23]:
array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

[1 2 3] int32


In [22]:
array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1 2 3] int32


# ndarray를 편리하게 생성하기-arange,zeros,ones
- 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야할 필요가 있는 경우가 발생할 수 있다.
- 주로 테스트용 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화 해야 할 경우에 사용됨
- 쉽게 array를 range() 로 표현할 것이다.

In [35]:
# default 함수 인자는 stop 값이며 0부터 stop값인 10에서 -1을 더한 9까지의 연속 숫자값으로 구성된 1차원ndarray를 만들어줌

sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [32]:
#zeros() 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환한다

zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [34]:
#ones()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환한다
# 함수인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채운다

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape()
- reshape 메서드는 ndarray를 특정 차원 및 크기로 변환함
- 변환을 원하는 크기를 함수 인자로 부여하면 됨

In [36]:
array1=np.arange(10)
print('array1\n', array1)

array1
 [0 1 2 3 4 5 6 7 8 9]


In [37]:
array2=array1.reshape(2,5)
print('array2:\n',array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
array3=array1.reshape(5,2)
print('array3:\n',array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [39]:
# reshape()는 지정된 사이즈로 변경이 불가능하면 오류가 발생합니다
# (10,)데이터를 (4,3)shape 형태로 변경할 수는 없습니다.
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

## reshape를 효율적으로 사용하기 <인자로 -1 적용>
- -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해줌

In [41]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [42]:
# 에러 발생
array1=np.array(10)
array4=array1.reshape(-1,4)

ValueError: cannot reshape array of size 1 into shape (4)

In [ ]:
#-1 인자는 reshape(-1,1)형태로 자주 사용됨
#reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러개의 로우를 가지되, 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장함
#여러개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용됨

In [44]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [47]:
# 3차원의 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [49]:
# 1차원의 ndarray를 2차원의 ndarry로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


# 넘파이의 ndarray의 데이터 세트 선택하기-인덱싱(indexing)
- 넘파이에서 ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록

In [52]:
#1. 특정 데이터만 추출
#2. 슬라이싱(slicing)
#3. 팬시 인덱싱(Fancy Indexing)
#4. 불린 인덱싱(Boolean indexing)

## 단일 값 추출
- 한개의 데이터만을 추출
- ndarray객체에 해당하는 위치의 인덱스 값을 []안에 입력

In [56]:
# 1부터 9까지 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
print('array1:',array1)

array1: [1 2 3 4 5 6 7 8 9]


In [57]:
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value=array1[2]
print('value:',value)
print(type(value))

value: 3
<class 'numpy.int32'>


In [60]:
# 인덱스 -1은 맨 뒤의 데이터 값을 의미
print('맨 뒤의 값:',array1[-1], '맨 뒤에서 두 번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [61]:
# 단일 인덱스를 이용해 ndarray 내의 데이터값도 간단히 수정 가능
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


## 다차원 ndarray에서 단일 값을 추출
- 1차원과 2차원 ndarry에서의 데이터 접근의 차이는
- 2차원은 콤마(,)로 분리된 로우와 칼럼의 위치를 인덱스를 통해 접근

In [66]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값: ',array2d[0,0])
print('(row=0, col=1) index 가리키는 값: ',array2d[0,1])
print('(row=1, col=0) index 가리키는 값: ',array2d[1,0])
print('(row=2, col=2) index 가리키는 값: ',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값:  1
(row=0, col=1) index 가리키는 값:  2
(row=1, col=0) index 가리키는 값:  4
(row=2, col=2) index 가리키는 값:  9


# 슬라이싱
- : 기호를 이용해 연속한 데이터를 슬라이싱 해 추출할 수 있음
- 단일 데이터 값 추출을 제외하고 슬라이싱, 팬시인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray타입이다.
- : 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1의 위치에 있는 데이터의 ndarray를 변환한다
- 슬라이싱 기호인 :사이의 시작, 종료 인덱스는 생략이 가능

In [67]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [68]:
# 1. :기호 앞에 시작인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주

array1=np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)

[1 2 3]


In [70]:
# 2. :기호 뒤에서 종료 인덱스를 생략하면 자동으로 마지막 인덱스로 간주

array5=array1[3:]
print(array5)

[4 5 6 7 8 9]


In [71]:
# 3. :기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

array6=array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


In [74]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
print('array2d[0:2,0:2]\n', array2d[0:2,0:2])
print('array2d[1:3,0:3]\n', array2d[1:3,0:3])
print('array2d[1:3,:]\n', array2d[1:3,0:])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2,1:]\n', array2d[:2,1:])
print('array2d[:2,0]\n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [75]:
# 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환
# array2d[0]과 같이 2차원에서 오는 인덱스를 없애면 로우 축(axis 0)의 첫번째 로우 ndarray를 반환하게 됨
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


# 팬시 인덱싱

In [80]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


# 불린 인덱스(T/F)
- 불린 인덱스는 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용됨

In [82]:
array1d=np.arange(start=1,stop=10)
#[]안에 array1d > 5 Boolean indexing을 적용
array3=array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [83]:
#넘파이 ndarry객체에 조건식을 할당

array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [85]:
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:' , array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [87]:
# 직접 인덱스 집합을 만들어 대입한 것과 동일
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


# 행렬 정렬-sort()
- 넘파이에서 호출 : np.sort()
- 행렬 자체에서 호출 : sort()
- 두 방식의 차이점은 
- np.sort()의 경우 원 행렬은 그대로 유지한 태 원 행렬의 정렬된 행렬은 반환하며
- ndarray.sort()는 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None입니다

In [89]:
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [90]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬', sort_array1_desc)

내림차순으로 정렬 [9 5 3 1]


In [91]:
# 행렬이 2차원 이상일 경우에 axis축 값 설정을 통해 로우 방향, 칼럼 방향 정렬을 수행할 수 있다.
array2d=np.array([[8,12],
                 [7,1 ]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬: \n',sort_array2d_axis1)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


## 정렬된 행렬의 인덱스를 반환하기
- 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용
- np.argsort()는 정렬 행렬의 행원본 행렬 인덱스를 ndarray형으로 반환한다

In [92]:
# np.argsort() 원본 행렬의 정렬시 행렬 인덱스 값
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬시 원본 행렬의 인덱스: [1 0 3 2]


In [93]:
# 내림차순으로 정령 시 원본 행렬의 인덱스
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


# 시험성적데이터

In [95]:
import numpy as np

name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])  #78 84 88 95 98
                                        #0 2  4  1  3
sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산

# 행렬 내적 (행렬 곱)

In [98]:
A=np.array([[1,2,3],
           [4,5,6]])
B=np.array([[7,8],
           [9,10],
           [11,12]])

dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


# 전치행렬
- 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치행렬이라고 함
- 2*2행렬 A가 있을 경우 A행렬의 1행2열의 원소를 2행 1열의 원소로,
- 2행 1열의 원소를 1행 2열의 원소로 교환되는 것

### transpose()

In [99]:
A=np.array([[1,2],
           [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
