In [25]:
import numpy as np
data2= np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])
data2

array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

In [26]:
row=np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col=np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

In [27]:
from scipy import sparse

In [28]:
sparse.coo_matrix((data2, (row, col))).toarray()

array([[0, 0, 1, 0, 0, 5],
       [1, 4, 0, 3, 2, 5],
       [0, 6, 0, 3, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 8],
       [1, 0, 0, 0, 0, 0]])

In [32]:
data2= np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])
row_index= np.array([0,2,7,9,10,12,13])
col=np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

In [37]:
sparse.csr_matrix((data2, col, row_index)).toarray()            

array([[0, 0, 1, 0, 0, 5],
       [1, 4, 0, 3, 2, 5],
       [0, 6, 0, 3, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 8],
       [1, 0, 0, 0, 0, 0]])

In [42]:
#sparse.csr_matrix((data2, col, row_index)).toarray()    \
sparse.csr_matrix((data2, (row_index, col)))

ValueError: row, column, and data array must all be the same length